export const SELECT_CHINA = 'SELECT_CHINA';
export const SELECT_FINAL = 'SELECT_FINAL';
export const SELECT_DISCIPLINE = 'SELECT_DISCIPLINE';
export const UPDATE_SPORTS_DATES = 'UPDATE_SPORTS_DATES';
export const EMPTY_SCHEDULE = 'EMPTY_SCHEDULE';
export const SELECT_DATE = 'SELECT_DATE';
export const FETCHING_SCHEDULE = 'FETCHING_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';