export default {
	SELECT_CHINA: 'SELECT_CHINA',
	SELECT_FINAL: 'SELECT_FINAL',
	SELECT_DISCIPLINE: 'SELECT_DISCIPLINE',
	UPDATE_SPORTS_DATES: 'UPDATE_SPORTS_DATES',
	EMPTY_SCHEDULE: 'EMPTY_SCHEDULE',
	SELECT_DATE: 'SELECT_DATE',
	FETCHING_SCHEDULE: 'FETCHING_SCHEDULE',
	UPDATE_SCHEDULE: 'UPDATE_SCHEDULE'
};