export const SELECT_CHINA = 'SELECT_CHINA';
export const SELECT_GOLD = 'SELECT_GOLD';
export const SELECT_DISCIPLINE = 'SELECT_DISCIPLINE';

export const UPDATE_SPORTS_DATES = 'UPDATE_SPORTS_DATES';
export const EMPTY_HOT_SCHEDULE = 'EMPTY_HOT_SCHEDULE';
export const EMPTY_MAIN_SCHEDULE = 'EMPTY_MAIN_SCHEDULE';

export const SELECT_DATE = 'SELECT_DATE';
export const FETCHING_HOT_SCHEDULE = 'FETCHING_HOT_SCHEDULE';
export const FETCHING_MAIN_SCHEDULE = 'FETCHING_MAIN_SCHEDULE';
export const UPDATE_HOT_SCHEDULE = 'UPDATE_HOT_SCHEDULE';
export const UPDATE_MAIN_SCHEDULE = 'UPDATE_MAIN_SCHEDULE';

export const TOGGLE_TOAST = 'TOGGLE_TOAST';